export const NOT_FOUND_ROUTE = '**';
export const APP_ROUTE = {
    AUTH: 'auth',
    MAIN: 'main',
    WORKSPACE: 'workspace',
    SOCIAL: 'social',
    DASHBOARD: 'dashboard'
};
export const AUTH_ROUTE = {
    LOGIN: 'login',
};
export const MAIN_ROUTE = {
    HOME: 'home',
    MY_BUSSINESSES: 'my_bussinesses',
    QUICK_CHAT: 'quick-chat',
    NOTIFICATION: 'notification',
    PROFILE: 'profile',
    CART: 'cart',
    SEARCH: 'search',
    ENTERPRISE: 'enterprise'
};
export const HOME_ROUTE = {
};
export const MY_BUSSINESSES_ROUTE = {
    LIST: 'list',
    ADD: 'add',
    JOIN: 'join',
};
// export const QUICK_CHAT_ROUTE = {

// };
// export const NOTIFICATION_ROUTE = {

// };
// export const PROFILE_ROUTE = {

// };
// export const CART_ROUTE = {

// };
// export const SEARCH_ROUTE = {

// };
export const MAIN_ENTERPRISE_ROUTE = {
    _ID_USAHA : ':idUsaha',

};
export const WORKSPACE_ROUTE = {
    _ID_USAHA : ':idUsaha',

    CASHIER: 'cashier',
    PRODUCT: 'product',

    RAW: 'raw',
    NOTIFICATION: 'notification',
    SCHEDULE: 'schedule',
    ORDER: 'order',
    NOT_ALLOWED: 'not_allowed',
};
export const WS_CASHIER = {
    _KEY_: 'CASHIER'
};
export const WS_PRODUCT = {
    _KEY_: 'PRODUCT',
    _ID_PRODUCT_INFO: ':idProductInfo',
    PRODUCT_ADD: 'add',
    PRODUCT_INFO: 'info',
    PRODUCT_UPDATE: 'update',
};
export const DASHBOARD_ROUTE = {
    _ID_USAHA : ':idUsaha',
    OVERVIEW: 'overview',
    PRODUCT: 'product',
    EMPLOYEE: 'employee',
    NOT_ALLOWED: 'not_allowed',
    TRANSACTION: 'transaction',

};
export const DASHBOARD_EMPLOYEE_ROUTE = {
    _KEY_: 'EMPLOYEE',
    LIST: 'list',
    ROLE: 'role',
};
export const DB_EMPY_ROLE_ROUTE = {
    _ID_ROLE: ':idRole',
    ROLE_ADD: 'add',
    ROLE_INFO: 'info'
};
export const DB_TRANS_ROUTE = {
    _KEY_: 'TRANSACTION',
    _ID_ORDER: ':idOrder',
    TRANS_DETAIL: 'detail',
    TRANS_LIST: 'list',
};
export const DB_OVERVIEW = {
    _KEY_: 'OVERVIEW'
};
export const GLOBAL_PATH = {
    AUTH: `/${APP_ROUTE.AUTH}`,
    AUTH_lOGIN: `/${APP_ROUTE.AUTH}/${AUTH_ROUTE.LOGIN}`,

    MAIN: `/${APP_ROUTE.MAIN}`,
    MAIN_HOME: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.HOME}`,
    MAIN_MY_BUSSINESSES: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.MY_BUSSINESSES}`,
    MAIN_MY_BUSSINESSES_LIST: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.MY_BUSSINESSES}/${MY_BUSSINESSES_ROUTE.LIST}`,
    MAIN_MY_BUSSINESSES_ADD: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.MY_BUSSINESSES}/${MY_BUSSINESSES_ROUTE.ADD}`,
    MAIN_MY_BUSSINESSES_JOIN: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.MY_BUSSINESSES}/${MY_BUSSINESSES_ROUTE.JOIN}`,
    MAIN_QUICK_CHAT: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.QUICK_CHAT}`,
    MAIN_NOTIFICATION: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.NOTIFICATION}`,
    MAIN_PROFILE: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.PROFILE}`,
    MAIN_CART: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.CART}`,
    MAIN_SEARCH: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.SEARCH}`,
    MAIN_ENTERPRISE: `/${APP_ROUTE.MAIN}/${MAIN_ROUTE.ENTERPRISE}/${MAIN_ENTERPRISE_ROUTE._ID_USAHA}`,

    WORKSPACE: `/${APP_ROUTE.WORKSPACE}`,
    WORKSPACE_CASHIER: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.CASHIER}`,
    WORKSPACE_PRODUCT: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.PRODUCT}`,
    WORKSPACE_PRODUCT_INFO: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.PRODUCT}/${WS_PRODUCT.PRODUCT_INFO}/${WS_PRODUCT._ID_PRODUCT_INFO}`,
    WORKSPACE_PRODUCT_UPDATE: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.PRODUCT}/${WS_PRODUCT.PRODUCT_UPDATE}/${WS_PRODUCT._ID_PRODUCT_INFO}`,
    WORKSPACE_PRODUCT_ADD: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.PRODUCT}/${WS_PRODUCT.PRODUCT_ADD}`,
    WORKSPACE_RAW: `/${APP_ROUTE.WORKSPACE}/${WORKSPACE_ROUTE._ID_USAHA}/${WORKSPACE_ROUTE.RAW}`,

    DASHBOARD: `/${APP_ROUTE.DASHBOARD}`,
    DASHBOARD_OVERVIEW: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.OVERVIEW}`,
    DASHBOARD_EMPLOYEE: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.EMPLOYEE}`,
    DASHBOARD_EMPLOYEE_LIST: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.EMPLOYEE}/${DASHBOARD_EMPLOYEE_ROUTE.LIST}`,
    DASHBOARD_EMPLOYEE_ROLE: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.EMPLOYEE}/${DASHBOARD_EMPLOYEE_ROUTE.ROLE}`,
    DASHBOARD_EMPLOYEE_ROLE_ADD: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.EMPLOYEE}/${DASHBOARD_EMPLOYEE_ROUTE.ROLE}/${DB_EMPY_ROLE_ROUTE.ROLE_ADD}`,
    DASHBOARD_EMPLOYEE_ROLE_INFO: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.EMPLOYEE}/${DASHBOARD_EMPLOYEE_ROUTE.ROLE}/${DB_EMPY_ROLE_ROUTE.ROLE_INFO}/${DB_EMPY_ROLE_ROUTE._ID_ROLE}`,

    DASHBOARD_TRANSACTION: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.TRANSACTION}`,
    DASHBOARD_TRANSACTION_DETAIL: `/${APP_ROUTE.DASHBOARD}/${DASHBOARD_ROUTE._ID_USAHA}/${DASHBOARD_ROUTE.TRANSACTION}/${DB_TRANS_ROUTE.TRANS_DETAIL}/${DB_TRANS_ROUTE._ID_ORDER}`,

    SOCIAL: `/${APP_ROUTE.SOCIAL}`,


};
